---
setup_brew: true
setup_zsh: true

# Set to 'true' to configure the Dock via dockutil.
configure_dock: true
dockitems_remove:
  - 'App Store'
  - 'System Preferences'
  - 'iPhone Mirroring'
  - Calendar
  - Contacts
  - FaceTime
  - Freeform
  - Launchpad
  - Maps
  - Messages
  - Music
  - News
  - Notes
  - Numbers
  - Pages
  - Photos
  - Podcasts
  - Reminders
  - Safari
  - TV
dockitems_persist:
  - name: 'Brave Browser'
    path: '/Applications/Brave Browser.app/'
    pos: 1
  - name: 'Alacritty'
    path: '/Applications/Alacritty.app/'
    pos: 2
  - name: 'Slack'
    path: '/Applications/Slack.app/'
    pos: 3
  - name: 'Mail'
    path: '/Applications/Mail.app/'
    pos: 4
  - name: 'Obsidian'
    path: '/Applications/Obsidian.app/'
    pos: 5

homebrew_installed_packages:
  - agg
  - ansible
  - ansible-lint
  - ant
  - aquaproj/aqua/aqua
  - aquasecurity/trivy/trivy
  - argocd
  - arping
  - asciinema
  - asdf
  - asitop
  - ast-grep
  - autoconf-archive
  - autogen
  - automake
  - aws-iam-authenticator
  - aws/tap/ec2-instance-selector
  - aws/tap/eks-node-viewer
  - awscli
  - awslogs
  - bash
  - bash-completion
  - bat
  - bottom
  - bzip2
  - cdk8s
  - charmbracelet/tap/freeze
  - chart-testing
  - checkov
  - chezmoi
  - cli53
  - cmctl
  - codespell
  - colordiff
  - container-diff
  - cookiecutter
  - coreutils
  - cosign
  - csvlens
  - cue
  - curl
  - cypher-shell
  - dasel
  - derailed/popeye/popeye
  - detect-secrets
  - direnv
  - dive
  - {name: docker, install_options: 'formula'}
  - docker-compose
  - docker-credential-helper
  - docker-credential-helper-ecr
  - docker-slim
  - dockutil
  - dos2unix
  - dotenv-linter
  - dust
  - eksctl
  - entr
  - eslint
  - expect
  - eza
  - faas-cli
  - fairwindsops/tap/nova
  - fairwindsops/tap/polaris
  - fastfetch
  - fd
  - ffmpeg
  - ffmpegthumbnailer
  - fzf
  - gh
  - ghq
  - gifsicle
  - gifski
  - git
  - git-cliff
  - git-delta
  - git-xargs
  - gitleaks
  - glances
  - glow
  - gnu-sed
  - gnupg
  - gnutls
  - go-jsonnet
  - goreleaser/tap/goreleaser
  - gradle
  - grafana
  - grafana-agent
  - grep
  - grpcurl
  - gstreamer
  - hadolint
  - helm
  - {name: hey, install_options: 'formula'}
  - hidapi
  - hopenpgp-tools
  - htop
  - httrack
  - iperf3
  - jdupes
  - jinja2-cli
  - jq
  - jsonnet-bundler
  - k2tf
  - k3d
  - k9s
  - krew
  - kube-linter
  - kube-ps1
  - kubeconform
  - kubectx
  - kubernetes-cli
  - kubescape/tap/kubescape-cli
  - kubeseal
  - kustomize
  - kwok
  - lazygit
  - libfido2
  - libheif
  - libpq
  - libxml2
  - lindell/multi-gitter/multi-gitter
  - logcli
  - luarocks
  - make
  - mas
  - maven
  - mike-engel/jwt-cli/jwt-cli
  - mimirtool
  - minikube
  - miniscruff/changie/changie
  - mise
  - mtr
  - mysql-client
  - ncurses
  - neomutt
  - neovim
  - nmap
  - node
  - norwoodj/tap/helm-docs
  - nvm
  - openjdk
  - openssh
  - openssl@3
  # - opentofu
  - ossp-uuid
  - osx-cpu-temp
  - oven-sh/bun/bun
  - pandoc
  - parallel
  - pdm
  - perl
  - pgcli
  - pinentry-mac
  - pipenv
  - pngpaste
  - poetry
  - popeye
  - postgresql@14
  - pre-commit
  - prettier
  - proselint
  - pwgen
  - pyenv
  - pyenv-virtualenv
  - readline
  - rename
  - ripgrep
  - rsync
  - ruby
  - ruff
  - rust
  - rye
  - screen
  - shellcheck
  - shfmt
  - skaffold
  - skopeo
  - socat
  - {name: spark, install_options: 'formula'}
  - sqlite
  - sslscan
  - starship
  - stern
  - stylua
  - tenv
  # - terraform
  # - terraform-docs
  # - terragrunt
  # - tlrc
  - tealdeer
  - terrascan
  - tflint
  - tfsec
  - theden/gcopy/gcopy
  - tmux
  - tokei
  - tree
  - trippy
  - updatecli
  - usage
  - uv
  - vale
  - velero
  - vhs
  - vim
  - watch
  - wget
  - whois
  - wireguard-tools
  - xz
  - yamlfmt
  - yamllint
  - yapf
  - yarn
  - yazi
  - ykman
  - ykpers
  - yq
  - yubico-piv-tool
  - yubikey-personalization
  - zlib
  - zoxide
  - zsh
  - zsh-vi-mode

homebrew_taps:
  - aquasecurity/trivy
  - aws/tap
  - charmbracelet/tap
  - derailed/popeye
  - fairwindsops/tap
  - goreleaser/tap
  - kubescape/tap
  - lindell/multi-gitter
  - mike-engel/jwt-cli
  - norwoodj/tap
  - oven-sh/bun
  - theden/gcopy
  - updatecli/updatecli
  - veeso/termscp
  - weaveworks/tap
  - name: miniscruff/changie
    url: 'https://github.com/miniscruff/changie'

homebrew_cask_appdir: /Applications
homebrew_cask_apps:
  - alacritty
  - betterdisplay
  - brave-browser
  - deskpad
  - elgato-camera-hub
  - elgato-control-center
  - elgato-stream-deck
  - elgato-wave-link
  - firefox
  - font-caskaydia-cove-nerd-font
  - font-droid-sans-mono-nerd-font
  - font-fira-code-nerd-font
  - font-hack-nerd-font
  - font-jetbrains-mono-nerd-font
  - font-symbols-only-nerd-font
  - ghostty
  - google-chrome
  - google-cloud-sdk
  - hiddenbar
  - homerow
  - iterm2
  - keycastr
  - keymapp
  - logi-options-plus
  # - logitech-g-hub # There is an issue with install. Download link here: https://download01.logi.com/web/ftp/pub/techsupport/gaming/lghub_installer.zip
  - maccy
  - neohtop
  - nikitabobko/tap/aerospace
  - obs
  - obsidian
  - rancher
  - slack
  - syncthing
  - tad
  - topnotch
  - visual-studio-code
  - vlc
  - yubico-authenticator
  - yubico-yubikey-manager
  - zoom

mas_installed_apps: []
