autocomplete = true
breaking_changes = true
issues = true
emoji = false
sign = true

[[commit_types]]
name = "feat"
emoji = "ğŸš€"
description = "A new feature"

[[commit_types]]
name = "fix"
emoji = "ğŸ›"
description = "A bug fix"

[[commit_types]]
name = "docs"
emoji = "ğŸ“š"
description = "Documentation only changes"

[[commit_types]]
name = "style"
emoji = "ğŸ¨"
description = "Changes that do not affect the meaning of the code"

[[commit_types]]
name = "refactor"
emoji = "ğŸšœ"
description = "A code change that neither fixes a bug nor adds a feature"

[[commit_types]]
name = "perf"
emoji = "âš¡"
description = "A code change that improves performance"

[[commit_types]]
name = "test"
emoji = "ğŸ§ª"
description = "Adding missing tests or correcting existing tests"

[[commit_types]]
name = "build"
emoji = "ğŸ”¨"
description = "Changes that affect the build system or external dependencies"

[[commit_types]]
name = "ci"
emoji = "ğŸ¤–"
description = "Changes to our CI configuration files and scripts"

[[commit_types]]
name = "chore"
emoji = "ğŸ§¹"
description = "Other changes that don't modify src or test files"

[[commit_types]]
name = "revert"
emoji = "âª"
description = "Reverts a previous commit"

[[commit_types]]
name = "security"
emoji = "ğŸš¨"
description = "Addresses a security issue"
